### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by jkoenig72** [featherbear/zifon-yt1000-wifi-mcu#5]
Hi,

interesting project. I have one of those yt-000 myself and try to replicate your work.

One question - when I compile the wifi-acu with VS it works and also I can upload. I see a gotpot PT-xxxxcxcxc created and I can join. However there is no wifi manager, open 192.168.4.1 in the browser gives me a 404: Not Found.

Guess I also need to upload the files in the http folder to the SPIFF FS, can you help a bit with this?

Thanks!
Joerg

**Comment by featherbear** [comment]
Hi!

To build the web components you'll need Node.js and yarn installed

1. Install project dependencies with `yarn install`
2. Build site with `yarn build`
3. In PlaformIO there should be a button to "upload file system"

**Comment by jkoenig72** [comment]
Ok, thanks. For the file system, within the "data" folder there is a "www"
folder, correct?

**Comment by jkoenig72** [comment]
done. within the yarn project, after building it, the files under the
public folder ("www" folder) that I need to transfer to the platformio data
folder and upload. correct?

**Comment by jkoenig72** [comment]
hmmm... can't get it to work. build works for both parts, upload seems ok
as well. Still 404: not found. That is the url to access the config ui?

192.168.4.1
192.168.4.1/index.html

???

**Comment by featherbear** [comment]
You shouldn't need to transfer any files manually, the the `yarn build` command builds the files into the [http]/public directory.

When you press Upload it should automatically source the files from that previously mentioned directory

**Comment by jkoenig72** [comment]
Yes. Thats what I see now. I use same board, wemos d1 mini.

Under Project Tasks I executed:
Build
Upload
Build Filesystem Image
Upload Filesystem Image

Again I can see the hotspot, I can join but if I open 192.168.4.1 - 404:
not found

Any idea what can go wrong?

**Comment by jkoenig72** [comment]
Looks good to me



 *  Executing task: C:\Users\fritz\.platformio\penv\Scripts\platformio.exe
run --target buildfs --environment esp8266

Processing esp8266 (platform: ***@***.***; board: d1_mini;
framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.2.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.20.0
|-- WebSockets @ 2.3.7
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- Ethernet @ 2.0.0
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- ESP8266mDNS @ 1.2
|   |-- ESP8266WiFi @ 1.0
|-- LittleFS @ 0.1.0
|-- Hash @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
Building in release mode
Building file system image from
'C:\Users\fritz\Documents\visualstudio\acu\http\public' directory to
.pio\build\esp8266\littlefs.bin
/www/app/bundle.css
/www/app/bundle.js
===================================================================================================
[SUCCESS] Took 1.66 seconds
===================================================================================================
 *  Terminal will be reused by tasks, press any key to close it.

 *  Executing task: C:\Users\fritz\.platformio\penv\Scripts\platformio.exe
run --target buildfs --environment esp8266

Processing esp8266 (platform: ***@***.***; board: d1_mini;
framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.2.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.20.0
|-- WebSockets @ 2.3.7
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- Ethernet @ 2.0.0
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- ESP8266mDNS @ 1.2
|   |-- ESP8266WiFi @ 1.0
|-- LittleFS @ 0.1.0
|-- Hash @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
Building in release mode
Building file system image from
'C:\Users\fritz\Documents\visualstudio\acu\http\public' directory to
.pio\build\esp8266\littlefs.bin
/www/app/bundle.css
/www/app/bundle.js
===================================================================================================
[SUCCESS] Took 2.38 seconds
===================================================================================================
 *  Terminal will be reused by tasks, press any key to close it.

 *  Executing task: C:\Users\fritz\.platformio\penv\Scripts\platformio.exe
run --target buildfs --environment esp8266

Processing esp8266 (platform: ***@***.***; board: d1_mini;
framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.2.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.20.0
|-- WebSockets @ 2.3.7
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- Ethernet @ 2.0.0
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- ESP8266mDNS @ 1.2
|   |-- ESP8266WiFi @ 1.0
|-- LittleFS @ 0.1.0
|-- Hash @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
Building in release mode
Building file system image from
'C:\Users\fritz\Documents\visualstudio\acu\http\public' directory to
.pio\build\esp8266\littlefs.bin
/www/app/bundle.css
/www/app/bundle.js
===================================================================================================
[SUCCESS] Took 1.65 seconds
===================================================================================================
 *  Terminal will be reused by tasks, press any key to close it.

 *  Executing task: C:\Users\fritz\.platformio\penv\Scripts\platformio.exe
run --target buildfs --environment esp8266

Processing esp8266 (platform: ***@***.***; board: d1_mini;
framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.2.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.20.0
|-- WebSockets @ 2.3.7
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- Ethernet @ 2.0.0
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- ESP8266mDNS @ 1.2
|   |-- ESP8266WiFi @ 1.0
|-- LittleFS @ 0.1.0
|-- Hash @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
Building in release mode
Building file system image from
'C:\Users\fritz\Documents\visualstudio\acu\http\public' directory to
.pio\build\esp8266\littlefs.bin
/www/app/bundle.css
/www/app/bundle.js
===================================================================================================
[SUCCESS] Took 1.65 seconds
===================================================================================================
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by jkoenig72** [comment]
Works now. I was simply too stupid. thx!

**Comment by featherbear** [comment]
Awesome!

What did you do wrong? Would be great to jot it down in case someone else makes the same mistake down the track!

**Comment by jkoenig72** [comment]
I simply do not execute the yarn build with teh files from the repo. Those
were missing. I did a fresh:

1.) checkout your repo
2.) build the yarn part 2 new files are created
3.) import into VS
4.) build and upload the esp8266 image within VS
5.) build the file system image within VS and upload it
6.) all works
